# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "i2c-dev" "vfio" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/78c76d4b-6c8c-4077-88bc-c6663bb184ad";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=90" ];
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/AEC2-6A03";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
    "/media/data" = {
      device = "/dev/disk/by-uuid/0EE2D775E2D7600F";
      fsType = "ntfs";
      options = [ "defaults" "autodefrag" "noatime" "compress=zstd:13" ];
    };
   # "/media/ssd" = {
   #   device = "/dev/disk/by-uuid/e13f03e7-bb0d-443f-acfe-cce36179a71a";
   #   options = [ "rw" "noatime" "compress=zstd:1" "ssd" "discard=async" "space_cache=v2" "commit=90" ];
   # };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
